"use client"

import Link from "next/link"
import { useMemo, useState } from "react"
import { Download, PackageSearch, Search, SlidersHorizontal, Upload } from "lucide-react"

import { useMemba } from "@/components/memba-provider"
import { buttonVariants } from "@/components/ui/button"
import { adjustInventorySchema } from "@/lib/memba/catalogue-schemas"
import { cn } from "@/lib/utils"

const money = new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" })

export function InventoryPage() {
  const { adjustInventory, data, membership, organization } = useMemba()
  const [query, setQuery] = useState("")
  const [locationId, setLocationId] = useState("ALL")
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState<string | null>(null)
  const [importing, setImporting] = useState(false)
  const organizationId = organization?.id ?? (membership.role === "SUPER_ADMIN" ? data.organizations[0]?.id : membership.organizationId)
  const locations = data.locations.filter((item) => item.organizationId === organizationId && item.active)
  const rows = useMemo(() => data.inventory.flatMap((record) => { if (record.organizationId !== organizationId || (locationId !== "ALL" && record.locationId !== locationId)) return []; const variant = data.variants.find((item) => item.id === record.variantId); const product = data.products.find((item) => item.id === variant?.productId); const location = data.locations.find((item) => item.id === record.locationId); if (!variant || !product || !location || !product.active) return []; const text = `${product.name} ${product.designNumber} ${variant.sku} ${variant.barcode} ${variant.colour} ${location.name}`.toLowerCase(); return text.includes(query.toLowerCase()) ? [{ record, variant, product, location }] : [] }), [data.inventory, data.locations, data.products, data.variants, locationId, organizationId, query])
  function downloadExample() { const csv = "sku,location_code,quantity_change,reason,notes\nMR266-CRGR-160230,RCH,12,Initial stock,Opening stock count\nMR266-CRGR-160230,PRE,-1,Damaged item,Removed after inspection\n"; const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "memba-inventory-import-example.csv"; anchor.click(); URL.revokeObjectURL(url) }
  async function importCsv(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file || !organizationId || !["SUPER_ADMIN", "ADMIN"].includes(membership.role)) return; setImporting(true); setError(null); setSuccess(null); try { const lines = (await file.text()).split(/\r?\n/).map((line) => line.trim()).filter(Boolean); const headers = lines.shift()?.split(",").map((item) => item.trim().toLowerCase()) ?? []; const required = ["sku", "location_code", "quantity_change", "reason", "notes"]; if (required.some((field) => !headers.includes(field))) throw new Error(`CSV must include: ${required.join(", ")}.`); let count = 0; for (const line of lines) { const values = line.split(",").map((item) => item.trim()); const row = Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ""])); const variant = data.variants.find((item) => item.organizationId === organizationId && item.sku === row.sku.toUpperCase()); const location = locations.find((item) => item.code.toLowerCase() === row.location_code.toLowerCase()); if (!variant || !location) throw new Error(`Could not match SKU ${row.sku} or location ${row.location_code}.`); const parsed = adjustInventorySchema.safeParse({ organizationId, variantId: variant.id, locationId: location.id, quantityChange: Number(row.quantity_change), reason: row.reason, notes: row.notes }); if (!parsed.success) throw new Error(`Invalid row for ${row.sku}: ${parsed.error.issues[0]?.message}`); adjustInventory(parsed.data); count++ } setSuccess(`${count} inventory row${count === 1 ? "" : "s"} imported.`) } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not import this CSV.") } finally { setImporting(false) } }
  return <div className="mx-auto max-w-[1440px] px-4 py-6 md:px-6 lg:px-8 lg:py-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">{organization?.name ?? "Inventory"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Inventory</h1><p className="mt-2 text-sm text-muted-foreground">Search availability across stores and warehouses.</p></div><div className="flex flex-wrap gap-2"><Link href="/inventory/adjust" className={cn(buttonVariants(), "min-h-11")}><SlidersHorizontal className="size-4" aria-hidden="true" />Adjust stock</Link>{["SUPER_ADMIN", "ADMIN"].includes(membership.role) && <><button type="button" onClick={downloadExample} className={cn(buttonVariants({ variant: "outline" }), "min-h-11")}><Download className="size-4" aria-hidden="true" />CSV example</button><label className={cn(buttonVariants({ variant: "outline" }), "min-h-11 cursor-pointer")}><Upload className="size-4" aria-hidden="true" />{importing ? "Importing…" : "Import CSV"}<input type="file" accept=".csv,text/csv" onChange={importCsv} disabled={importing} className="sr-only" /></label></>}</div></div>
    <div className="mt-5 flex flex-wrap gap-2"><Link href="/inventory/overview" className={cn(buttonVariants({ variant: "outline" }), "min-h-11")}>Stock overview</Link><Link href="/inventory/movements" className={cn(buttonVariants({ variant: "outline" }), "min-h-11")}>Movement ledger</Link>{["SUPER_ADMIN", "ADMIN"].includes(membership.role) && <Link href="/products/variants/new" className={cn(buttonVariants({ variant: "outline" }), "min-h-11")}>Add variant</Link>}</div>
    {(error || success) && <p role={error ? "alert" : "status"} className={cn("mt-4 rounded-md px-3 py-2 text-sm", error ? "bg-destructive/10 text-destructive" : "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300")}>{error ?? success}</p>}
    <section className="mt-7 rounded-xl border bg-card"><div className="grid gap-3 border-b p-4 md:grid-cols-[1fr_15rem]"><label className="relative"><span className="sr-only">Search inventory</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search SKU, barcode, design, colour…" className="h-11 w-full rounded-md border bg-background pl-10 pr-3 text-sm focus-visible:ring-2 focus-visible:ring-ring" /></label><label><span className="sr-only">Location</span><select value={locationId} onChange={(event) => setLocationId(event.target.value)} className="h-11 w-full rounded-md border bg-background px-3 text-sm"><option value="ALL">All locations</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b bg-muted/30 text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">Product</th><th className="px-3 py-3 font-medium">Location</th><th className="px-3 py-3 text-right font-medium">On hand</th><th className="px-3 py-3 text-right font-medium">Reserved</th><th className="px-3 py-3 text-right font-medium">Available</th><th className="px-3 py-3 text-right font-medium">Retail</th></tr></thead><tbody>{rows.map(({ record, variant, product, location }) => { const available = record.quantityOnHand - record.quantityReserved; return <tr key={record.id} className="border-b last:border-0"><td className="px-4 py-4"><p className="text-sm font-medium">{product.name}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{variant.sku} · {variant.colour} · {variant.widthCm}×{variant.lengthCm}</p></td><td className="px-3 py-4 text-sm text-muted-foreground">{location.name}</td><td className="px-3 py-4 text-right font-mono text-sm tabular-nums">{record.quantityOnHand}</td><td className="px-3 py-4 text-right font-mono text-sm tabular-nums">{record.quantityReserved}</td><td className="px-3 py-4 text-right"><span className={cn("inline-flex min-w-8 justify-center rounded-full px-2 py-1 font-mono text-xs font-medium", available > 0 ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" : "bg-destructive/10 text-destructive")}>{available}</span></td><td className="px-3 py-4 text-right font-mono text-sm">{money.format(variant.retailPriceCents / 100)}</td></tr> })}</tbody></table></div> : <div className="px-6 py-16 text-center"><PackageSearch className="mx-auto size-9 text-muted-foreground" aria-hidden="true" /><h2 className="mt-4 font-medium">No inventory found</h2><p className="mt-1 text-sm text-muted-foreground">Change the search or location filter.</p></div>}</section>
  </div>
}
