"use client"

import Link from "next/link"
import { ArrowLeft, ClipboardList } from "lucide-react"

import { useMemba } from "@/components/memba-provider"

export function InventoryMovementsPage() {
  const { data, membership, organization } = useMemba()
  const organizationId = organization?.id ?? (membership.role === "SUPER_ADMIN" ? data.organizations[0]?.id : membership.organizationId)
  const movements = data.inventoryMovements.filter((item) => item.organizationId === organizationId)
  return <div className="mx-auto max-w-[1440px] px-4 py-6 md:px-6 lg:px-8 lg:py-8"><Link href="/inventory" className="inline-flex min-h-10 items-center gap-2 text-sm text-muted-foreground hover:text-foreground focus-visible:ring-2 focus-visible:ring-ring"><ArrowLeft className="size-4" aria-hidden="true" />Inventory</Link><div className="mt-5 flex items-end gap-3"><ClipboardList className="size-7 text-primary" aria-hidden="true" /><div><p className="text-sm font-medium text-primary">{organization?.name ?? "Inventory"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Movement ledger</h1><p className="mt-2 text-sm text-muted-foreground">Latest immutable inventory events.</p></div></div><section className="mt-7 overflow-hidden rounded-xl border bg-card">{movements.length ? <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead><tr className="border-b bg-muted/30 text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">Time</th><th className="px-3 py-3 font-medium">SKU</th><th className="px-3 py-3 font-medium">Location</th><th className="px-3 py-3 font-medium">Reason</th><th className="px-3 py-3 text-right font-medium">Change</th><th className="px-4 py-3 text-right font-medium">After</th></tr></thead><tbody>{movements.map((movement) => { const variant = data.variants.find((item) => item.id === movement.variantId); const location = data.locations.find((item) => item.id === movement.locationId); return <tr key={movement.id} className="border-b last:border-0 text-sm"><td className="px-4 py-4 text-xs text-muted-foreground">{new Date(movement.createdAt).toLocaleString("en-AU")}</td><td className="px-3 py-4 font-mono text-xs">{variant?.sku ?? "—"}</td><td className="px-3 py-4 text-muted-foreground">{location?.name ?? "—"}</td><td className="px-3 py-4 text-xs text-muted-foreground">{movement.reason}</td><td className={movement.quantityChange > 0 ? "px-3 py-4 text-right font-mono text-emerald-700 dark:text-emerald-300" : "px-3 py-4 text-right font-mono text-destructive"}>{movement.quantityChange > 0 ? "+" : ""}{movement.quantityChange}</td><td className="px-4 py-4 text-right font-mono">{movement.quantityAfter}</td></tr> })}</tbody></table></div> : <p className="px-6 py-16 text-center text-sm text-muted-foreground">No inventory movements yet.</p>}</section></div>
}
