"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import { Boxes, ClipboardList, Download, PackagePlus, PackageSearch, Search, SlidersHorizontal, Upload } from "lucide-react"

import { useMemba } from "@/components/memba-provider"
import { buttonVariants } from "@/components/ui/button"
import { adjustInventorySchema, buildRugSku } from "@/lib/memba/catalogue-schemas"
import type { AdjustInventoryInput } from "@/lib/memba/types"
import type { Location, MembaData, Product, ProductVariant } from "@/lib/memba/types"
import { cn } from "@/lib/utils"

const money = new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" })

export function InventoryPage() {
  const { adjustInventory, data, membership, organization } = useMemba(); const [query, setQuery] = useState(""); const [locationId, setLocationId] = useState("ALL"); const [adjustVariantId, setAdjustVariantId] = useState(""); const [adjustLocationId, setAdjustLocationId] = useState(""); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [importing, setImporting] = useState(false)
  const organizationId = organization?.id ?? (membership.role === "SUPER_ADMIN" ? data.organizations[0]?.id : membership.organizationId)
  const locations = data.locations.filter((item) => item.organizationId === organizationId && item.active)
  const canAdjust = ["SUPER_ADMIN","ADMIN","STORE_MANAGER"].includes(membership.role)
  const rows = useMemo(() => data.inventory.flatMap((record) => { if (record.organizationId !== organizationId || (locationId !== "ALL" && record.locationId !== locationId)) return []; const variant = data.variants.find((item) => item.id === record.variantId); const product = data.products.find((item) => item.id === variant?.productId); const location = data.locations.find((item) => item.id === record.locationId); if (!variant || !product || !location || !product.active) return []; const text = `${product.name} ${product.designNumber} ${variant.sku} ${variant.barcode} ${variant.colour} ${location.name}`.toLowerCase(); return text.includes(query.toLowerCase()) ? [{ record, variant, product, location }] : [] }), [data.inventory, data.locations, data.products, data.variants, locationId, organizationId, query])
  const movements = data.inventoryMovements.filter((item) => item.organizationId === organizationId).slice(0, 20)
  function openAdjustment(variantId: string, nextLocationId: string) { setAdjustVariantId(variantId); setAdjustLocationId(nextLocationId); setError(null); setSuccess(null); requestAnimationFrame(() => document.querySelector<HTMLElement>("#adjustment-form")?.scrollIntoView({ behavior: "smooth", block: "center" })) }
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const input: AdjustInventoryInput = { organizationId: organizationId ?? "", variantId: adjustVariantId, locationId: adjustLocationId, quantityChange: Number(values.get("quantityChange")), reason: String(values.get("reason") ?? ""), notes: String(values.get("notes") ?? "") }; const parsed = adjustInventorySchema.safeParse(input); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Check the adjustment."); return } try { adjustInventory(parsed.data); event.currentTarget.reset(); setSuccess("Stock updated and movement recorded."); setError(null) } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not update stock.") } }
  function downloadExample() { const csv = "product_id,colour,length_cm,width_cm,location_code,quantity_change,reason,notes\nMR266,Grey Cream,160,230,RCH,12,Initial stock,Opening stock count\nMR266,Grey Cream,160,230,PRE,-1,Damaged item,Removed after inspection\n"; const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "memba-inventory-import-example.csv"; anchor.click(); URL.revokeObjectURL(url) }
  async function importCsv(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file || !organizationId || !["SUPER_ADMIN", "ADMIN"].includes(membership.role)) return; setImporting(true); setError(null); setSuccess(null); try { const lines = (await file.text()).split(/\r?\n/).map((line) => line.trim()).filter(Boolean); const headers = lines.shift()?.split(",").map((item) => item.trim().toLowerCase()) ?? []; const required = ["product_id", "colour", "length_cm", "width_cm", "location_code", "quantity_change", "reason", "notes"]; if (required.some((field) => !headers.includes(field))) throw new Error(`CSV must include: ${required.join(", ")}.`); let count = 0; for (const line of lines) { const values = line.split(",").map((item) => item.trim()); const row = Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ""])); const sku = buildRugSku(row.product_id, row.colour, Number(row.length_cm), Number(row.width_cm)); const variant = data.variants.find((item) => item.organizationId === organizationId && item.sku === sku); const location = locations.find((item) => item.code.toLowerCase() === row.location_code.toLowerCase()); if (!variant || !location) throw new Error(`Could not match calculated SKU or location.`); const parsed = adjustInventorySchema.safeParse({ organizationId, variantId: variant.id, locationId: location.id, quantityChange: Number(row.quantity_change), reason: row.reason, notes: row.notes }); if (!parsed.success) throw new Error(`Invalid row for ${row.sku}: ${parsed.error.issues[0]?.message}`); adjustInventory(parsed.data); count++ } setSuccess(`${count} inventory row${count === 1 ? "" : "s"} imported.`) } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not import this CSV.") } finally { setImporting(false) } }
  return <div className="mx-auto max-w-[1440px] px-4 py-6 md:px-6 lg:px-8 lg:py-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">{organization?.name ?? "Inventory"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Inventory</h1><p className="mt-2 text-sm text-muted-foreground">Search availability across stores and warehouses.</p></div>{canAdjust && <div className="flex flex-wrap gap-2"><button type="button" onClick={() => document.querySelector<HTMLElement>("#adjustment-form")?.scrollIntoView({ behavior: "smooth", block: "center" })} className={cn(buttonVariants(), "min-h-11")}><PackagePlus className="size-4" aria-hidden="true" />Add stock</button>{["SUPER_ADMIN", "ADMIN"].includes(membership.role) && <><button type="button" onClick={downloadExample} className={cn(buttonVariants({ variant: "outline" }), "min-h-11")}><Download className="size-4" aria-hidden="true" />CSV example</button><label className={cn(buttonVariants({ variant: "outline" }), "min-h-11 cursor-pointer")}><Upload className="size-4" aria-hidden="true" />{importing ? "Importing…" : "Import CSV"}<input type="file" accept=".csv,text/csv" onChange={importCsv} disabled={importing} className="sr-only" /></label></>}</div>}</div>
    <div className="mt-5 flex flex-wrap gap-2"><Link href="/inventory/adjust" className={cn(buttonVariants(), "min-h-11")}>Adjust stock</Link>{["SUPER_ADMIN", "ADMIN"].includes(membership.role) && <Link href="/products/variants/new" className={cn(buttonVariants({ variant: "outline" }), "min-h-11")}>Add variant</Link>}</div><InventoryMatrix data={data} organizationId={organizationId ?? undefined} locations={locations} />
    <section className="mt-7 rounded-xl border bg-card"><div className="grid gap-3 border-b p-4 md:grid-cols-[1fr_15rem]"><label className="relative"><span className="sr-only">Search inventory</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search SKU, barcode, design, colour…" className="h-11 w-full rounded-md border bg-background pl-10 pr-3 text-sm focus-visible:ring-2 focus-visible:ring-ring" /></label><label><span className="sr-only">Location</span><select value={locationId} onChange={(event) => setLocationId(event.target.value)} className="h-11 w-full rounded-md border bg-background px-3 text-sm"><option value="ALL">All locations</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>
      {rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b bg-muted/30 text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">Product</th><th className="px-3 py-3 font-medium">Location</th><th className="px-3 py-3 text-right font-medium">On hand</th><th className="px-3 py-3 text-right font-medium">Reserved</th><th className="px-3 py-3 text-right font-medium">Available</th><th className="px-3 py-3 text-right font-medium">Retail</th><th className="px-4 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(({ record, variant, product, location }) => { const available = record.quantityOnHand - record.quantityReserved; return <tr key={record.id} className="border-b last:border-0"><td className="px-4 py-4"><p className="text-sm font-medium">{product.name}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{variant.sku} · {variant.colour} · {variant.widthCm}×{variant.lengthCm}</p></td><td className="px-3 py-4 text-sm text-muted-foreground">{location.name}</td><td className="px-3 py-4 text-right font-mono text-sm tabular-nums">{record.quantityOnHand}</td><td className="px-3 py-4 text-right font-mono text-sm tabular-nums">{record.quantityReserved}</td><td className="px-3 py-4 text-right"><span className={cn("inline-flex min-w-8 justify-center rounded-full px-2 py-1 font-mono text-xs font-medium", available > 0 ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" : "bg-destructive/10 text-destructive")}>{available}</span></td><td className="px-3 py-4 text-right font-mono text-sm">{money.format(variant.retailPriceCents / 100)}</td><td className="px-4 py-4 text-right">{canAdjust && <button type="button" onClick={() => openAdjustment(variant.id, location.id)} className={cn(buttonVariants({ variant: "outline", size: "sm" }), "min-h-10")}><SlidersHorizontal className="size-4" aria-hidden="true" />Adjust</button>}</td></tr> })}</tbody></table></div> : <div className="px-6 py-16 text-center"><PackageSearch className="mx-auto size-9 text-muted-foreground" aria-hidden="true" /><h2 className="mt-4 font-medium">No inventory found</h2><p className="mt-1 text-sm text-muted-foreground">Change the search or location filter.</p></div>}
    </section>
    {canAdjust && <section id="adjustment-form" className="mt-6 rounded-xl border bg-card p-5 md:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-secondary"><SlidersHorizontal className="size-4" aria-hidden="true" /></span><div><h2 className="font-semibold">Stock adjustment</h2><p className="mt-1 text-xs text-muted-foreground">Every change is permanently recorded.</p></div></div><form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="space-y-1.5"><span className="text-sm font-medium">Variant</span><select value={adjustVariantId} onChange={(event) => setAdjustVariantId(event.target.value)} className="h-11 w-full rounded-md border bg-background px-3 text-sm"><option value="">Select variant</option>{data.variants.filter((item) => item.organizationId === organizationId && item.active).map((variant) => <option key={variant.id} value={variant.id}>{variant.sku}</option>)}</select></label><label className="space-y-1.5"><span className="text-sm font-medium">Location</span><select value={adjustLocationId} onChange={(event) => setAdjustLocationId(event.target.value)} className="h-11 w-full rounded-md border bg-background px-3 text-sm"><option value="">Select location</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="space-y-1.5"><span className="text-sm font-medium">Quantity change</span><input name="quantityChange" inputMode="numeric" placeholder="-1 or 3" className="h-11 w-full rounded-md border bg-background px-3 font-mono text-sm" /></label><label className="space-y-1.5"><span className="text-sm font-medium">Reason</span><select name="reason" className="h-11 w-full rounded-md border bg-background px-3 text-sm"><option value="">Select reason</option>{["Stocktake correction","Damaged item","Lost item","Supplier return","Initial stock","Other"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="space-y-1.5 md:col-span-2 xl:col-span-3"><span className="text-sm font-medium">Notes</span><input name="notes" placeholder="Explain what changed" className="h-11 w-full rounded-md border bg-background px-3 text-sm" /></label><button type="submit" className={cn(buttonVariants(), "min-h-11 self-end")}>Record adjustment</button>{error && <p role="alert" className="md:col-span-2 xl:col-span-4 rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p>}{success && <p role="status" className="md:col-span-2 xl:col-span-4 rounded-md bg-emerald-500/10 px-3 py-2 text-sm text-emerald-700 dark:text-emerald-300">{success}</p>}</form></section>}
    <section className="mt-6 rounded-xl border bg-card"><div className="flex items-center gap-3 border-b px-5 py-4"><ClipboardList className="size-4 text-muted-foreground" aria-hidden="true" /><div><h2 className="font-semibold">Movement ledger</h2><p className="mt-1 text-xs text-muted-foreground">Latest immutable inventory events</p></div></div>{movements.length ? <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead><tr className="border-b bg-muted/30 text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">Time</th><th className="px-3 py-3 font-medium">SKU</th><th className="px-3 py-3 font-medium">Location</th><th className="px-3 py-3 font-medium">Type</th><th className="px-3 py-3 text-right font-medium">Change</th><th className="px-4 py-3 text-right font-medium">After</th></tr></thead><tbody>{movements.map((movement) => { const variant = data.variants.find((item) => item.id === movement.variantId); const location = data.locations.find((item) => item.id === movement.locationId); return <tr key={movement.id} className="border-b last:border-0 text-sm"><td className="px-4 py-4 text-xs text-muted-foreground">{new Date(movement.createdAt).toLocaleString("en-AU")}</td><td className="px-3 py-4 font-mono text-xs">{variant?.sku}</td><td className="px-3 py-4 text-muted-foreground">{location?.name}</td><td className="px-3 py-4 text-xs text-muted-foreground">{movement.reason}</td><td className={cn("px-3 py-4 text-right font-mono", movement.quantityChange > 0 ? "text-emerald-700 dark:text-emerald-300" : "text-destructive")}>{movement.quantityChange > 0 ? "+" : ""}{movement.quantityChange}</td><td className="px-4 py-4 text-right font-mono">{movement.quantityAfter}</td></tr> })}</tbody></table></div> : <div className="px-6 py-14 text-center"><Boxes className="mx-auto size-8 text-muted-foreground" aria-hidden="true" /><p className="mt-3 text-sm font-medium">No movements yet</p><p className="mt-1 text-xs text-muted-foreground">Stock changes will appear here.</p></div>}</section>
  </div>
}

function InventoryMatrix({ data, organizationId, locations }: { data: MembaData; organizationId: string | undefined; locations: Location[] }) { const products = data.variants.filter((variant) => variant.organizationId === organizationId && variant.active).map((variant) => ({ product: data.products.find((product) => product.id === variant.productId), variant })).filter((item): item is { product: Product; variant: ProductVariant } => Boolean(item.product)); return <section className="mt-6 rounded-xl border bg-card"><div className="border-b px-5 py-4"><h2 className="font-semibold">All locations overview</h2><p className="mt-1 text-xs text-muted-foreground">Products are rows, locations are columns, with grand totals.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead><tr className="border-b bg-muted/30 text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">Product</th>{locations.map((location) => <th key={location.id} className="px-3 py-3 text-right font-medium">{location.code}</th>)}<th className="px-4 py-3 text-right font-medium">Row total</th></tr></thead><tbody>{products.map(({ product, variant }) => <tr key={product.id} className="border-b last:border-0"><td className="px-4 py-4"><p className="text-sm font-medium">{product.name}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{variant?.sku}</p></td>{locations.map((location) => <td key={location.id} className="px-3 py-4 text-right font-mono text-sm">{data.inventory.find((record) => record.variantId === variant?.id && record.locationId === location.id)?.quantityOnHand ?? 0}</td>)}<td className="px-4 py-4 text-right font-mono text-sm font-semibold">{locations.reduce((sum, location) => sum + (data.inventory.find((record) => record.variantId === variant?.id && record.locationId === location.id)?.quantityOnHand ?? 0), 0)}</td></tr>)}</tbody><tfoot><tr className="bg-muted/40 text-sm font-semibold"><td className="px-4 py-4">Grand total</td>{locations.map((location) => <td key={location.id} className="px-3 py-4 text-right font-mono">{products.reduce((sum, { variant }) => sum + (data.inventory.find((record) => record.variantId === variant?.id && record.locationId === location.id)?.quantityOnHand ?? 0), 0)}</td>)}<td className="px-4 py-4 text-right font-mono">{products.reduce((sum, { variant }) => sum + locations.reduce((total, location) => total + (data.inventory.find((record) => record.variantId === variant?.id && record.locationId === location.id)?.quantityOnHand ?? 0), 0), 0)}</td></tr></tfoot></table></div></section> }
