"use client"

import Link from "next/link"
import { ArrowLeft, Boxes } from "lucide-react"

import { useMemba } from "@/components/memba-provider"
import { buttonVariants } from "@/components/ui/button"
import { cn } from "@/lib/utils"

export function InventoryOverviewPage() {
  const { data, membership, organization } = useMemba()
  const organizationId = organization?.id ?? (membership.role === "SUPER_ADMIN" ? data.organizations[0]?.id : membership.organizationId)
  const locations = data.locations.filter((item) => item.organizationId === organizationId && item.active)
  const variants = data.variants.filter((item) => item.organizationId === organizationId && item.active).map((variant) => ({ variant, product: data.products.find((item) => item.id === variant.productId) })).filter((item): item is { variant: typeof item.variant; product: NonNullable<typeof item.product> } => Boolean(item.product))
  return <div className="mx-auto max-w-[1440px] px-4 py-6 md:px-6 lg:px-8 lg:py-8"><Link href="/inventory" className="inline-flex min-h-10 items-center gap-2 text-sm text-muted-foreground hover:text-foreground focus-visible:ring-2 focus-visible:ring-ring"><ArrowLeft className="size-4" aria-hidden="true" />Inventory</Link><div className="mt-5 flex items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">{organization?.name ?? "Inventory"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Stock overview</h1><p className="mt-2 text-sm text-muted-foreground">Products are rows and locations are columns, with grand totals.</p></div><Boxes className="size-8 text-primary" aria-hidden="true" /></div><section className="mt-7 overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b bg-muted/30 text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">Product</th>{locations.map((location) => <th key={location.id} className="px-3 py-3 text-right font-medium">{location.code}</th>)}<th className="px-4 py-3 text-right font-medium">Row total</th></tr></thead><tbody>{variants.map(({ product, variant }) => <tr key={variant.id} className="border-b last:border-0"><td className="px-4 py-4"><p className="text-sm font-medium">{product.name}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{variant.sku}</p></td>{locations.map((location) => <td key={location.id} className="px-3 py-4 text-right font-mono text-sm">{data.inventory.find((record) => record.variantId === variant.id && record.locationId === location.id)?.quantityOnHand ?? 0}</td>)}<td className="px-4 py-4 text-right font-mono text-sm font-semibold">{locations.reduce((sum, location) => sum + (data.inventory.find((record) => record.variantId === variant.id && record.locationId === location.id)?.quantityOnHand ?? 0), 0)}</td></tr>)}</tbody><tfoot><tr className="bg-muted/40 text-sm font-semibold"><td className="px-4 py-4">Grand total</td>{locations.map((location) => <td key={location.id} className="px-3 py-4 text-right font-mono">{variants.reduce((sum, { variant }) => sum + (data.inventory.find((record) => record.variantId === variant.id && record.locationId === location.id)?.quantityOnHand ?? 0), 0)}</td>)}<td className="px-4 py-4 text-right font-mono">{variants.reduce((sum, { variant }) => sum + locations.reduce((total, location) => total + (data.inventory.find((record) => record.variantId === variant.id && record.locationId === location.id)?.quantityOnHand ?? 0), 0), 0)}</td></tr></tfoot></table></div>{!variants.length && <p className="px-6 py-16 text-center text-sm text-muted-foreground">No active products yet.</p>}</section><Link href="/inventory" className={cn(buttonVariants({ variant: "outline" }), "mt-5 min-h-11")}>Back to inventory</Link></div>
}
