"use client"

import { FormEvent, useState } from "react"
import { Eye, EyeOff, Globe2, LockKeyhole, Mail } from "lucide-react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"

export function LoginForm() {
  const router = useRouter(); const [showPassword, setShowPassword] = useState(false); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false)
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!email.trim() || !password) { setError("Enter your email and password to continue."); return } setLoading(true); router.push("/dashboard") }
  function google() { setLoading(true); router.push("/dashboard") }
  return <section className="rounded-3xl border bg-card p-6 shadow-xl shadow-primary/10 md:p-8"><div><p className="text-sm font-medium text-primary">Welcome back</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Sign in to Memba</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Use the email from your invitation. New accounts are created by your organisation admin.</p></div><Button type="button" variant="outline" className="mt-7 h-12 w-full" onClick={google} disabled={loading}><Globe2 className="size-4" aria-hidden="true" />Continue with Google</Button><div className="my-6 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border" /><span>or continue with email</span><span className="h-px flex-1 bg-border" /></div><form onSubmit={submit} className="space-y-4"><div><label htmlFor="email" className="mb-1.5 block text-sm font-medium">Work email</label><div className="relative"><Mail className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><input id="email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@company.com" className="h-12 w-full rounded-md border bg-background pl-10 pr-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /></div></div><div><div className="mb-1.5 flex items-center justify-between"><label htmlFor="password" className="text-sm font-medium">Password</label><button type="button" className="text-xs font-medium text-primary hover:underline">Forgot password?</button></div><div className="relative"><LockKeyhole className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><input id="password" type={showPassword ? "text" : "password"} autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" className="h-12 w-full rounded-md border bg-background px-10 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((visible) => !visible)} className="absolute right-3 top-1/2 -translate-y-1/2 rounded p-1 text-muted-foreground hover:text-foreground focus-visible:ring-2 focus-visible:ring-ring">{showPassword ? <EyeOff className="size-4" aria-hidden="true" /> : <Eye className="size-4" aria-hidden="true" />}</button></div></div>{error && <p className="text-sm text-destructive" role="alert">{error}</p>}<Button type="submit" className="h-12 w-full" disabled={loading}>{loading ? "Opening workspace…" : "Sign in"}</Button></form><p className="mt-6 text-center text-xs leading-5 text-muted-foreground">Access is invite-only. Contact your organisation administrator if you need an invitation.</p></section>
}
