"use client"

import Link from "next/link"
import { ReceiptText, ShoppingBag } from "lucide-react"

import { useMemba } from "@/components/memba-provider"
import { buttonVariants } from "@/components/ui/button"
import { cn } from "@/lib/utils"

const money = new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" })
const statusLabels: Record<string, string> = { DRAFT: "Draft", QUOTE: "Quote", PARTIALLY_PAID: "Partially paid", PAID_UNFULFILLED: "Paid · unfulfilled", COMPLETED: "Paid", VOID: "Void", CANCELLED: "Cancelled", REFUNDED: "Refunded" }

export function OrdersPage() {
  const { data, membership, organization } = useMemba(); const organizationId = organization?.id ?? (membership.role === "SUPER_ADMIN" ? data.organizations[0]?.id : membership.organizationId); const orders = data.orders.filter((item) => item.organizationId === organizationId)
  return <div className="mx-auto max-w-[1440px] px-4 py-6 md:px-6 lg:px-8 lg:py-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">{organization?.name ?? "Sales"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Orders</h1><p className="mt-2 text-sm text-muted-foreground">Quotes, payments and fulfilment records.</p></div><Link href="/sales/new" className={cn(buttonVariants({ size: "lg" }), "min-h-11")}>New sale</Link></div><section className="mt-7 rounded-xl border bg-card">{orders.length ? <div className="overflow-x-auto"><table className="w-full min-w-[750px] text-left"><thead><tr className="border-b bg-muted/30 text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">Order</th><th className="px-3 py-3 font-medium">Date</th><th className="px-3 py-3 font-medium">Items</th><th className="px-3 py-3 font-medium">Payment</th><th className="px-3 py-3 text-right font-medium">Total</th><th className="px-4 py-3"><span className="sr-only">Status</span></th></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-b last:border-0"><td className="px-4 py-4"><div className="flex items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-secondary"><ReceiptText className="size-4" aria-hidden="true" /></span><Link href={`/orders/${order.id}`} className="rounded-md focus-visible:ring-2 focus-visible:ring-ring"><span className="block font-mono text-sm font-medium">{order.orderNumber}</span><span className="mt-1 block text-xs text-muted-foreground">{data.users.find((item) => item.id === order.salespersonUserId)?.name}</span></Link></div></td><td className="px-3 py-4 text-xs text-muted-foreground">{new Date(order.createdAt).toLocaleString("en-AU")}</td><td className="px-3 py-4 text-sm text-muted-foreground">{order.items.reduce((sum, item) => sum + item.qty, 0)} items</td><td className="px-3 py-4 text-xs font-medium">{order.paymentMethod ?? "—"}</td><td className="px-3 py-4 text-right font-mono text-sm font-semibold">{money.format(order.totalCents / 100)}</td><td className="px-4 py-4 text-right"><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-medium">{statusLabels[order.status] ?? order.status}</span></td></tr>)}</tbody></table></div> : <div className="px-6 py-20 text-center"><ShoppingBag className="mx-auto size-10 text-muted-foreground" aria-hidden="true" /><h2 className="mt-4 font-medium">No orders yet</h2><p className="mt-1 text-sm text-muted-foreground">Completed sales will appear here.</p><Link href="/sales/new" className={cn(buttonVariants({ variant: "outline" }), "mt-5")}>Start a sale</Link></div>}</section></div>
}
