"use client"

import Link from "next/link"
import { ArrowLeft, Building2, MapPin, ShieldCheck, Store, UserRound, Warehouse } from "lucide-react"

import { useState } from "react"
import { useMemba } from "@/components/memba-provider"
import { buttonVariants } from "@/components/ui/button"
import { cn } from "@/lib/utils"

export function OrganizationDetail({ organizationId }: { organizationId: string }) {
  const { data, membership, setOrganizationLocationLimit } = useMemba()
  const organization = data.organizations.find((item) => item.id === organizationId)

  if (membership.role !== "SUPER_ADMIN") return <State title="Super admin access required" description="This organization is outside your current permission scope." />
  if (!organization) return <State title="Organization not found" description="It may have been removed from this local development dataset." />

  const locations = data.locations.filter((item) => item.organizationId === organization.id)
  const memberships = data.memberships.filter((item) => item.organizationId === organization.id)
  const auditLogs = data.auditLogs.filter((item) => item.organizationId === organization.id)
  const activeLocationCount = locations.filter((item) => item.active).length

  return <div className="mx-auto max-w-[1440px] px-4 py-6 md:px-6 lg:px-8 lg:py-8">
    <Link href="/organizations" className="inline-flex min-h-10 items-center gap-2 rounded-md text-sm text-muted-foreground hover:text-foreground focus-visible:ring-2 focus-visible:ring-ring"><ArrowLeft className="size-4" aria-hidden="true" />Organizations</Link>
    <div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-secondary"><Building2 className="size-5" aria-hidden="true" /></span><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-semibold tracking-tight">{organization.name}</h1><span className="rounded-full bg-amber-500/10 px-2.5 py-1 text-xs font-medium text-amber-700 dark:text-amber-300">{organization.status === "TRIAL" ? "Trial" : organization.status === "ACTIVE" ? "Active" : "Inactive"}</span></div><p className="mt-2 font-mono text-sm text-muted-foreground">{organization.code}</p></div></div><button type="button" className={cn(buttonVariants({ variant: "outline", size: "lg" }), "min-h-11")}>Edit organization</button></div>

    <div className="mt-8 grid gap-6 xl:grid-cols-2">
      <section className="rounded-xl border bg-card"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Locations</h2><p className="mt-1 text-xs text-muted-foreground">{activeLocationCount} active of {organization.maxLocations} allowed</p></div><Link href={`/organizations/${organization.id}/locations`} className={buttonVariants({ variant: "outline", size: "sm" })}>Manage</Link></div><div className="divide-y">{locations.map((location) => { const Icon = location.type === "STORE" ? Store : Warehouse; return <div key={location.id} className="flex items-center gap-3 px-5 py-4"><span className="grid size-10 place-items-center rounded-lg bg-secondary"><Icon className="size-4" aria-hidden="true" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{location.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="size-3" aria-hidden="true" />{location.suburb}, {location.state}</p></div><span className="font-mono text-xs text-muted-foreground">{location.code}</span></div> })}</div><LocationLimit organizationId={organization.id} current={organization.maxLocations} active={activeLocationCount} onSave={setOrganizationLocationLimit} /></section>
      <section className="rounded-xl border bg-card"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">People</h2><p className="mt-1 text-xs text-muted-foreground">Organization memberships</p></div><Link href={`/organizations/${organization.id}/people`} className={buttonVariants({ variant: "outline", size: "sm" })}>Manage</Link></div><div className="divide-y">{memberships.map((item) => { const person = data.users.find((candidate) => candidate.id === item.userId); return <div key={item.id} className="flex items-center gap-3 px-5 py-4"><span className="grid size-10 place-items-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">{person?.initials}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{person?.name}</p><p className="mt-1 truncate text-xs text-muted-foreground">{person?.email}</p></div><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-medium">{item.role === "ADMIN" ? "Admin" : item.role === "STORE_MANAGER" ? "Manager" : "Staff"}</span></div> })}</div></section>
    </div>

    <section className="mt-6 rounded-xl border bg-card"><div className="border-b px-5 py-4"><h2 className="font-semibold">Audit activity</h2><p className="mt-1 text-xs text-muted-foreground">Platform-level actions for this organization</p></div>{auditLogs.length ? <div className="divide-y">{auditLogs.map((log) => <div key={log.id} className="flex gap-3 px-5 py-4"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-secondary"><ShieldCheck className="size-4" aria-hidden="true" /></span><div><p className="text-sm font-medium">{log.description}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(log.timestamp).toLocaleString("en-AU")}</p></div></div>)}</div> : <div className="px-5 py-12 text-center"><UserRound className="mx-auto size-8 text-muted-foreground" aria-hidden="true" /><p className="mt-3 text-sm font-medium">No audited actions yet</p><p className="mt-1 text-xs text-muted-foreground">Organization creation and impersonation events appear here.</p></div>}</section>
  </div>
}

function LocationLimit({ organizationId, current, active, onSave }: { organizationId: string; current: number; active: number; onSave: (organizationId: string, limit: number) => void }) { const [value, setValue] = useState(String(current)); const [message, setMessage] = useState<string | null>(null); function submit(event: React.FormEvent) { event.preventDefault(); setMessage(null); try { onSave(organizationId, Number(value)); setMessage("Location limit saved.") } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save limit.") } } return <form onSubmit={submit} className="border-t bg-muted/20 px-5 py-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><label className="block max-w-xs flex-1 space-y-1.5"><span className="text-sm font-medium">Allowed locations</span><input type="number" min={active} value={value} onChange={(event) => setValue(event.target.value)} className="h-10 w-full rounded-md border bg-background px-3 font-mono text-sm" /></label><button type="submit" className={buttonVariants({ size: "sm" })}>Save limit</button></div>{message && <p className="mt-2 text-xs text-muted-foreground">{message}</p>}</form> }

function State({ title, description }: { title: string; description: string }) { return <div className="mx-auto max-w-xl px-4 py-20 text-center"><Building2 className="mx-auto size-10 text-muted-foreground" aria-hidden="true" /><h1 className="mt-5 text-2xl font-semibold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{description}</p><Link href="/organizations" className={cn(buttonVariants({ variant: "outline" }), "mt-6")}>Return to organizations</Link></div> }
