"use client"

import Link from "next/link"
import { useMemo, useState } from "react"
import { Archive, PackageOpen, Plus, Search } from "lucide-react"

import { useMemba } from "@/components/memba-provider"
import { buttonVariants } from "@/components/ui/button"
import { cn } from "@/lib/utils"

const money = new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" })

export function ProductsPage() {
  const { data, membership, organization, setProductActive } = useMemba()
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("ALL"); const [showArchived, setShowArchived] = useState(false)
  const organizationId = organization?.id ?? (membership.role === "SUPER_ADMIN" ? data.organizations[0]?.id : membership.organizationId)
  const categories = [...new Set(data.products.filter((item) => item.organizationId === organizationId).map((item) => item.category))].sort()
  const rows = useMemo(() => data.variants.flatMap((variant) => { const product = data.products.find((item) => item.id === variant.productId); if (!product || product.organizationId !== organizationId || (!showArchived && !product.active) || (category !== "ALL" && product.category !== category)) return []; const haystack = `${product.name} ${product.designNumber} ${product.category} ${product.collection} ${variant.sku} ${variant.barcode} ${variant.colour}`.toLowerCase(); return haystack.includes(query.toLowerCase()) ? [{ product, variant }] : [] }), [category, data.products, data.variants, organizationId, query, showArchived])
  const canEdit = membership.role === "SUPER_ADMIN" || membership.role === "ADMIN"

  return <div className="mx-auto max-w-[1440px] px-4 py-6 md:px-6 lg:px-8 lg:py-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">{organization?.name ?? "Catalogue"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Products</h1><p className="mt-2 text-sm text-muted-foreground">Product families and their sellable variants.</p></div>{canEdit && <Link href="/products/new" className={cn(buttonVariants({ size: "lg" }), "min-h-11")}><Plus className="size-4" aria-hidden="true" />New product</Link>}</div>
    <section className="mt-7 rounded-xl border bg-card"><div className="grid gap-3 border-b p-4 md:grid-cols-[1fr_13rem_auto]"><label className="relative"><span className="sr-only">Search products</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search SKU, design, colour, barcode…" className="h-11 w-full rounded-md border bg-background pl-10 pr-3 text-sm focus-visible:ring-2 focus-visible:ring-ring" /></label><label><span className="sr-only">Category</span><select value={category} onChange={(event) => setCategory(event.target.value)} className="h-11 w-full rounded-md border bg-background px-3 text-sm"><option value="ALL">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label className="flex min-h-11 items-center gap-2 rounded-md border px-3 text-sm"><input type="checkbox" checked={showArchived} onChange={(event) => setShowArchived(event.target.checked)} className="size-4 accent-primary" />Show archived</label></div>
      {rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="border-b bg-muted/30 text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">Product</th><th className="px-3 py-3 font-medium">SKU</th><th className="px-3 py-3 font-medium">Variant</th><th className="px-3 py-3 font-medium">Category</th><th className="px-3 py-3 text-right font-medium">Retail</th><th className="px-4 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(({ product, variant }) => <tr key={variant.id} className="border-b last:border-0"><td className="px-4 py-4"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-lg bg-secondary"><PackageOpen className="size-5" aria-hidden="true" /></span><div><p className="text-sm font-medium">{product.name}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{product.designNumber}</p></div></div></td><td className="px-3 py-4 font-mono text-xs">{variant.sku}</td><td className="px-3 py-4 text-sm text-muted-foreground">{variant.colour} · {variant.widthCm} × {variant.lengthCm} cm</td><td className="px-3 py-4 text-sm text-muted-foreground">{product.category}</td><td className="px-3 py-4 text-right font-mono text-sm tabular-nums">{money.format(variant.retailPriceCents / 100)}</td><td className="px-4 py-4 text-right">{canEdit && <button type="button" onClick={() => setProductActive(product.id, !product.active)} className={cn(buttonVariants({ variant: "ghost", size: "sm" }), "min-h-10")}><Archive className="size-4" aria-hidden="true" />{product.active ? "Archive" : "Restore"}</button>}</td></tr>)}</tbody></table></div> : <div className="px-6 py-16 text-center"><PackageOpen className="mx-auto size-9 text-muted-foreground" aria-hidden="true" /><h2 className="mt-4 font-medium">No products found</h2><p className="mt-1 text-sm text-muted-foreground">Change the search or category filter.</p><button type="button" onClick={() => { setQuery(""); setCategory("ALL") }} className={cn(buttonVariants({ variant: "outline" }), "mt-4")}>Clear filters</button></div>}
    </section>
  </div>
}
