"use client"

import { useMemo, useState } from "react"
import { CircleDollarSign, PackageOpen, ReceiptText, TrendingUp } from "lucide-react"

import { useMemba } from "@/components/memba-provider"

const money = new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD", maximumFractionDigits: 0 })

export function ReportsPage() {
  const { data, membership, organization } = useMemba(); const [period, setPeriod] = useState("TODAY"); const [locationId, setLocationId] = useState("ALL"); const [today] = useState(() => new Date().toDateString()); const [now] = useState(() => Date.now()); const organizationId = organization?.id ?? (membership.role === "SUPER_ADMIN" ? data.organizations[0]?.id : membership.organizationId); const locations = data.locations.filter((item) => item.organizationId === organizationId); const orders = useMemo(() => { const cutoff = period === "TODAY" ? undefined : now - (period === "7D" ? 7 : 30) * 24 * 60 * 60 * 1000; return data.orders.filter((order) => { const createdAt = new Date(order.createdAt); const inPeriod = cutoff === undefined ? createdAt.toDateString() === today : createdAt.getTime() >= cutoff; return order.organizationId === organizationId && (locationId === "ALL" || order.locationId === locationId) && inPeriod }) }, [data.orders, locationId, now, organizationId, period, today]); const revenue = orders.reduce((sum, order) => sum + order.totalCents, 0) + (period === "TODAY" && locationId === "ALL" ? data.organizations.find((item) => item.id === organizationId)?.salesTodayCents ?? 0 : 0); const cash = orders.filter((order) => order.paymentMethod === "CASH").reduce((sum, order) => sum + order.totalCents, 0); const eft = orders.filter((order) => order.paymentMethod === "EFT").reduce((sum, order) => sum + order.totalCents, 0); const gst = orders.reduce((sum, order) => sum + order.gstTotalCents, 0); const inventory = data.inventory.filter((item) => item.organizationId === organizationId && (locationId === "ALL" || item.locationId === locationId)).reduce((sum, record) => { const variant = data.variants.find((item) => item.id === record.variantId); return sum + (variant?.retailPriceCents ?? 0) * record.quantityOnHand }, 0)
  const hasOrders = orders.length > 0
  return <div className="mx-auto max-w-[1440px] px-4 py-6 md:px-6 lg:px-8 lg:py-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">{organization?.name ?? "Business reporting"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Reports</h1><p className="mt-2 text-sm text-muted-foreground">Sales, payments, GST and inventory value in one view.</p></div><div className="flex flex-wrap gap-2"><select value={period} onChange={(event) => setPeriod(event.target.value)} className="h-11 rounded-md border bg-background px-3 text-sm"><option value="TODAY">Today</option><option value="7D">Last 7 days</option><option value="30D">Last 30 days</option></select><select value={locationId} onChange={(event) => setLocationId(event.target.value)} className="h-11 rounded-md border bg-background px-3 text-sm"><option value="ALL">All locations</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div></div>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={TrendingUp} label="Revenue" value={money.format(revenue / 100)} note={`${orders.length} recorded orders`} /><Metric icon={ReceiptText} label="Orders" value={String(orders.length || (period === "TODAY" ? data.organizations.find((item) => item.id === organizationId)?.orderCountToday ?? 0 : 0))} note="Completed sales" /><Metric icon={CircleDollarSign} label="GST collected" value={money.format(gst / 100)} note="Included in sale totals" /><Metric icon={PackageOpen} label="Inventory retail value" value={money.format(inventory / 100)} note="On-hand stock" /></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-xl border bg-card"><div className="border-b px-5 py-4"><h2 className="font-semibold">Payment reconciliation</h2><p className="mt-1 text-xs text-muted-foreground">Recorded payments for the selected scope</p></div><div className="grid gap-3 p-5 sm:grid-cols-2"><Metric icon={CircleDollarSign} label="Cash" value={money.format(cash / 100)} note="Count against till" /><Metric icon={CircleDollarSign} label="EFT" value={money.format(eft / 100)} note="Match terminal totals" /></div></section><section className="rounded-xl border bg-card"><div className="border-b px-5 py-4"><h2 className="font-semibold">Operational follow-up</h2><p className="mt-1 text-xs text-muted-foreground">Required actions now live on the dashboard.</p></div><div className="p-5 text-sm text-muted-foreground">Use the dashboard for store-day controls, transfer actions and low-stock follow-up.</div></section></div>
    {!hasOrders && <div className="mt-6 rounded-xl border border-dashed p-8 text-center"><ReceiptText className="mx-auto size-8 text-muted-foreground" aria-hidden="true" /><p className="mt-3 text-sm font-medium">No recorded orders in this filter</p><p className="mt-1 text-xs text-muted-foreground">The seeded organization totals appear above; completed POS orders will populate detailed payment and GST rows.</p></div>}
  </div>
}
function Metric({ icon: Icon, label, value, note }: { icon: typeof TrendingUp; label: string; value: string; note: string }) { return <article className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2 text-muted-foreground"><Icon className="size-4" aria-hidden="true" /><p className="text-sm font-medium">{label}</p></div><p className="mt-3 font-mono text-2xl font-semibold tabular-nums tracking-tight">{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></article> }
