"use client"

import { useMemo, useState } from "react"
import { BarChart3, CircleDollarSign, ClipboardCheck, PackageOpen, ReceiptText, TrendingUp } from "lucide-react"

import { useMemba } from "@/components/memba-provider"
import type { DailyRegister } from "@/lib/memba/types"
import { cn } from "@/lib/utils"

const money = new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD", maximumFractionDigits: 0 })

export function ReportsPage() {
  const { data, endDay, openDay, membership, organization } = useMemba(); const [period, setPeriod] = useState("TODAY"); const [locationId, setLocationId] = useState("ALL"); const [countedCash, setCountedCash] = useState(""); const [dayError, setDayError] = useState<string | null>(null); const [daySuccess, setDaySuccess] = useState<string | null>(null); const [today] = useState(() => new Date().toDateString()); const [todayKey] = useState(() => new Date().toISOString().slice(0, 10)); const [now] = useState(() => Date.now()); const organizationId = organization?.id ?? (membership.role === "SUPER_ADMIN" ? data.organizations[0]?.id : membership.organizationId); const locations = data.locations.filter((item) => item.organizationId === organizationId); const orders = useMemo(() => { const cutoff = period === "TODAY" ? undefined : now - (period === "7D" ? 7 : 30) * 24 * 60 * 60 * 1000; return data.orders.filter((order) => { const createdAt = new Date(order.createdAt); const inPeriod = cutoff === undefined ? createdAt.toDateString() === today : createdAt.getTime() >= cutoff; return order.organizationId === organizationId && (locationId === "ALL" || order.locationId === locationId) && inPeriod }) }, [data.orders, locationId, now, organizationId, period, today]); const revenue = orders.reduce((sum, order) => sum + order.totalCents, 0) + (period === "TODAY" && locationId === "ALL" ? data.organizations.find((item) => item.id === organizationId)?.salesTodayCents ?? 0 : 0); const cash = orders.filter((order) => order.paymentMethod === "CASH").reduce((sum, order) => sum + order.totalCents, 0); const eft = orders.filter((order) => order.paymentMethod === "EFT").reduce((sum, order) => sum + order.totalCents, 0); const gst = orders.reduce((sum, order) => sum + order.gstTotalCents, 0); const inventory = data.inventory.filter((item) => item.organizationId === organizationId && (locationId === "ALL" || item.locationId === locationId)).reduce((sum, record) => { const variant = data.variants.find((item) => item.id === record.variantId); return sum + (variant?.retailPriceCents ?? 0) * record.quantityOnHand }, 0); const pendingTransfers = data.transfers.filter((item) => item.organizationId === organizationId && ["REQUESTED","APPROVED","IN_TRANSIT"].includes(item.status)).length; const register = locationId === "ALL" ? undefined : data.dailyRegisters.find((item) => item.organizationId === organizationId && item.locationId === locationId && item.businessDate === todayKey)
  function startDay() { if (!organizationId || locationId === "ALL") return; try { openDay(organizationId, locationId); setDaySuccess("Day opened. Staff can now trade from this location."); setDayError(null) } catch (error) { setDayError(error instanceof Error ? error.message : "Could not open the day.") } }
  function closeDay() { if (!register) return; try { endDay(register.id, Math.round(Number(countedCash || 0) * 100)); setDaySuccess("Day ended and cash variance recorded."); setDayError(null) } catch (error) { setDayError(error instanceof Error ? error.message : "Could not end the day.") } }
  const hasOrders = orders.length > 0
  return <div className="mx-auto max-w-[1440px] px-4 py-6 md:px-6 lg:px-8 lg:py-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">{organization?.name ?? "Business reporting"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Reports</h1><p className="mt-2 text-sm text-muted-foreground">Sales, payments, GST and inventory value in one view.</p></div><div className="flex flex-wrap gap-2"><select value={period} onChange={(event) => setPeriod(event.target.value)} className="h-11 rounded-md border bg-background px-3 text-sm"><option value="TODAY">Today</option><option value="7D">Last 7 days</option><option value="30D">Last 30 days</option></select><select value={locationId} onChange={(event) => setLocationId(event.target.value)} className="h-11 rounded-md border bg-background px-3 text-sm"><option value="ALL">All locations</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div></div>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={TrendingUp} label="Revenue" value={money.format(revenue / 100)} note={`${orders.length} recorded orders`} /><Metric icon={ReceiptText} label="Orders" value={String(orders.length || (period === "TODAY" ? data.organizations.find((item) => item.id === organizationId)?.orderCountToday ?? 0 : 0))} note="Completed sales" /><Metric icon={CircleDollarSign} label="GST collected" value={money.format(gst / 100)} note="Included in sale totals" /><Metric icon={PackageOpen} label="Inventory retail value" value={money.format(inventory / 100)} note="On-hand stock" /></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-xl border bg-card"><div className="border-b px-5 py-4"><h2 className="font-semibold">Payment reconciliation</h2><p className="mt-1 text-xs text-muted-foreground">Recorded payments for the selected scope</p></div><div className="grid gap-3 p-5 sm:grid-cols-2"><Metric icon={CircleDollarSign} label="Cash" value={money.format(cash / 100)} note="Count against till" /><Metric icon={CircleDollarSign} label="EFT" value={money.format(eft / 100)} note="Match terminal totals" /></div><div className="flex items-start gap-3 border-t p-5"><ClipboardCheck className="mt-0.5 size-4 text-muted-foreground" aria-hidden="true" /><div><p className="text-sm font-medium">Daily close</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Reconcile cash and EFT before closing the selected location.</p></div><button type="button" className="ml-auto rounded-md border px-3 py-2 text-xs font-medium hover:bg-accent focus-visible:ring-2 focus-visible:ring-ring">Mark reviewed</button></div></section><DailyRegisterPanel register={register} locationId={locationId} cashCents={cash} countedCash={countedCash} setCountedCash={setCountedCash} onOpen={startDay} onEnd={closeDay} error={dayError} success={daySuccess} /><section className="rounded-xl border bg-card"><div className="border-b px-5 py-4"><h2 className="font-semibold">What needs attention</h2><p className="mt-1 text-xs text-muted-foreground">Operational follow-up</p></div><div className="divide-y"><div className="flex items-center gap-3 p-5"><BarChart3 className="size-4 text-muted-foreground" aria-hidden="true" /><div className="flex-1"><p className="text-sm font-medium">Transfers pending</p><p className="mt-1 text-xs text-muted-foreground">Requests, approvals and stock in transit</p></div><span className={cn("font-mono text-lg", pendingTransfers ? "text-amber-700 dark:text-amber-300" : "text-muted-foreground")}>{pendingTransfers}</span></div><div className="flex items-center gap-3 p-5"><PackageOpen className="size-4 text-muted-foreground" aria-hidden="true" /><div className="flex-1"><p className="text-sm font-medium">Low stock review</p><p className="mt-1 text-xs text-muted-foreground">Variants with two or fewer available items</p></div><span className="font-mono text-lg text-muted-foreground">{data.inventory.filter((item) => item.organizationId === organizationId && item.quantityOnHand - item.quantityReserved <= 2).length}</span></div></div></section></div>
    {!hasOrders && <div className="mt-6 rounded-xl border border-dashed p-8 text-center"><ReceiptText className="mx-auto size-8 text-muted-foreground" aria-hidden="true" /><p className="mt-3 text-sm font-medium">No recorded orders in this filter</p><p className="mt-1 text-xs text-muted-foreground">The seeded organization totals appear above; completed POS orders will populate detailed payment and GST rows.</p></div>}
  </div>
}
function Metric({ icon: Icon, label, value, note }: { icon: typeof TrendingUp; label: string; value: string; note: string }) { return <article className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2 text-muted-foreground"><Icon className="size-4" aria-hidden="true" /><p className="text-sm font-medium">{label}</p></div><p className="mt-3 font-mono text-2xl font-semibold tabular-nums tracking-tight">{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></article> }
function DailyRegisterPanel({ register, locationId, cashCents, countedCash, setCountedCash, onOpen, onEnd, error, success }: { register?: DailyRegister; locationId: string; cashCents: number; countedCash: string; setCountedCash: (value: string) => void; onOpen: () => void; onEnd: () => void; error: string | null; success: string | null }) { return <section className="mt-6 rounded-xl border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Register day</h2><p className="mt-1 text-xs text-muted-foreground">Open and end the till for a specific location.</p></div><span className={cn("rounded-full px-2.5 py-1 text-xs font-medium", register?.status === "OPEN" ? "bg-emerald-500/10 text-emerald-700" : "bg-muted text-muted-foreground")}>{register?.status ?? "NOT OPEN"}</span></div>{locationId === "ALL" ? <p className="mt-4 rounded-md bg-muted/50 px-3 py-3 text-xs text-muted-foreground">Select one location above to open or end its day.</p> : register?.status === "OPEN" ? <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end"><label className="flex-1 space-y-1.5"><span className="text-sm font-medium">Counted cash</span><input value={countedCash} onChange={(event) => setCountedCash(event.target.value)} inputMode="decimal" placeholder="0.00" className="h-11 w-full rounded-md border bg-background px-3 font-mono text-sm focus-visible:ring-2 focus-visible:ring-ring" /></label><div><p className="text-xs text-muted-foreground">Expected cash</p><p className="font-mono font-semibold">{money.format(cashCents / 100)}</p></div><button type="button" onClick={onEnd} className="min-h-11 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground hover:bg-primary/80">End day</button></div> : <div className="mt-4"><button type="button" onClick={onOpen} className="min-h-11 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground hover:bg-primary/80">Open new day</button>{register?.status === "CLOSED" && <p className="mt-3 text-xs text-muted-foreground">Ended {register.closedAt ? new Date(register.closedAt).toLocaleTimeString("en-AU") : "today"} · Variance {money.format((register.varianceCents ?? 0) / 100)}</p>}</div>}{(error || success) && <p role="status" className={cn("mt-4 rounded-md px-3 py-2 text-sm", error ? "bg-destructive/10 text-destructive" : "bg-emerald-500/10 text-emerald-700")}>{error ?? success}</p>}</section> }
