"use client"

import { useState } from "react"
import { Bell, Building2, Check, CircleUserRound, KeyRound, ShieldCheck, Users } from "lucide-react"

import { useMemba } from "@/components/memba-provider"
import { buttonVariants } from "@/components/ui/button"
import { cn } from "@/lib/utils"

const tabs = [
  { id: "profile", label: "My profile", icon: CircleUserRound },
  { id: "workspace", label: "Workspace", icon: Building2, roles: ["SUPER_ADMIN", "ADMIN"] },
  { id: "access", label: "Access & people", icon: Users, roles: ["SUPER_ADMIN", "ADMIN", "STORE_MANAGER"] },
  { id: "discount", label: "Discount approval", icon: KeyRound, roles: ["SUPER_ADMIN", "ADMIN", "STORE_MANAGER"] },
  { id: "notifications", label: "Notifications", icon: Bell },
] as const

export function SettingsPage() {
  const { data, membership, organization, setApprovalCode, user } = useMemba(); const [activeTab, setActiveTab] = useState("profile"); const visibleTabs = tabs.filter((tab) => !("roles" in tab) || (tab.roles as readonly string[]).includes(membership.role)); const [saved, setSaved] = useState(false); const [emailAlerts, setEmailAlerts] = useState(true); const [stockAlerts, setStockAlerts] = useState(true)
  function save() { setSaved(true); window.setTimeout(() => setSaved(false), 2200) }
  return <div className="mx-auto max-w-[1200px] px-4 py-6 md:px-6 lg:px-8 lg:py-8"><p className="text-sm font-medium text-primary">Workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Settings</h1><p className="mt-2 text-sm text-muted-foreground">Manage your profile, workspace preferences and access.</p><div className="mt-8 grid gap-7 lg:grid-cols-[15rem_1fr]"><nav className="flex gap-1 overflow-x-auto lg:block lg:space-y-1" aria-label="Settings sections">{visibleTabs.map((tab) => <button key={tab.id} type="button" onClick={() => setActiveTab(tab.id)} className={cn("flex min-h-11 shrink-0 items-center gap-3 rounded-md px-3 text-sm font-medium focus-visible:ring-2 focus-visible:ring-ring lg:w-full", activeTab === tab.id ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-accent hover:text-foreground")}><tab.icon className="size-4" aria-hidden="true" />{tab.label}</button>)}</nav><section className="rounded-xl border bg-card p-5 md:p-7">{activeTab === "profile" && <Profile user={user} membership={membership} organization={organization?.name} onSave={save} saved={saved} />}{activeTab === "workspace" && <Workspace organization={organization?.name} data={data} onSave={save} saved={saved} />}{activeTab === "access" && <Access data={data} organizationId={organization?.id ?? membership.organizationId} />}{activeTab === "discount" && <DiscountCode currentCode={membership.approvalCode} onSave={setApprovalCode} />}{activeTab === "notifications" && <Notifications emailAlerts={emailAlerts} stockAlerts={stockAlerts} setEmailAlerts={setEmailAlerts} setStockAlerts={setStockAlerts} onSave={save} saved={saved} />}</section></div></div>
}

function DiscountCode({ currentCode, onSave }: { currentCode?: string; onSave: (code: string) => void }) { const [code, setCode] = useState(currentCode ?? ""); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); function submit(event: React.FormEvent) { event.preventDefault(); setError(null); setMessage(null); try { onSave(code); setMessage("Approval code saved.") } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save the approval code.") } } return <Panel title="Discount approval" description="Set the code you use to approve item-level discounts entered by staff."><form onSubmit={submit} className="max-w-md space-y-4"><label className="block space-y-1.5"><span className="text-sm font-medium">Manager approval code</span><input type="password" inputMode="numeric" autoComplete="one-time-code" value={code} onChange={(event) => setCode(event.target.value)} placeholder="4–12 digits" className="h-11 w-full rounded-md border bg-background px-3 font-mono text-sm focus-visible:ring-2 focus-visible:ring-ring" /><span className="block text-xs text-muted-foreground">Required when a staff member applies a discount. Leave blank to clear your code.</span></label>{error && <p role="alert" className="rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p>}{message && <p role="status" className="rounded-md bg-emerald-500/10 px-3 py-2 text-sm text-emerald-700 dark:text-emerald-300">{message}</p>}<button type="submit" className={cn(buttonVariants(), "min-h-11")}>Save approval code</button></form></Panel> }

function Profile({ user, membership, organization, onSave, saved }: { user: { name: string; email: string }; membership: { role: string }; organization?: string; onSave: () => void; saved: boolean }) { return <Panel title="My profile" description="Your identity and current workspace access."><div className="grid gap-4 sm:grid-cols-2"><ReadOnly label="Full name" value={user.name} /><ReadOnly label="Email" value={user.email} /><ReadOnly label="Role" value={membership.role.replaceAll("_", " ")} /><ReadOnly label="Organisation" value={organization ?? "Platform"} /></div><div className="mt-6 flex items-center gap-3 border-t pt-5"><button type="button" onClick={onSave} className={cn(buttonVariants(), "min-h-11")}>{saved ? <><Check className="size-4" />Saved</> : "Save profile"}</button><p className="text-xs text-muted-foreground">Profile changes will be managed through Clerk after authentication is connected.</p></div></Panel> }
function Workspace({ organization, data, onSave, saved }: { organization?: string; data: { locations: Array<unknown>; memberships: Array<unknown> }; onSave: () => void; saved: boolean }) { return <Panel title="Workspace" description="Organisation-level preferences and operating context."><div className="grid gap-4 sm:grid-cols-2"><ReadOnly label="Organisation" value={organization ?? "All organisations"} /><ReadOnly label="Locations" value={String(data.locations.length)} /><ReadOnly label="People" value={String(data.memberships.length)} /><ReadOnly label="Primary category" value="Rugs" /></div><label className="mt-6 block space-y-1.5"><span className="text-sm font-medium">Default currency</span><select className="h-11 w-full rounded-md border bg-background px-3 text-sm" defaultValue="AUD"><option>AUD — Australian Dollar</option><option>NZD — New Zealand Dollar</option></select></label><button type="button" onClick={onSave} className={cn(buttonVariants(), "mt-6 min-h-11")}>{saved ? "Saved" : "Save workspace"}</button></Panel> }
function Access({ data, organizationId }: { data: { users: Array<{ id: string; name: string; email: string; active: boolean }>; memberships: Array<{ userId: string; organizationId: string | null; role: string }> }; organizationId: string | null }) { const people = data.memberships.filter((item) => item.organizationId === organizationId).map((membership) => ({ membership, user: data.users.find((user) => user.id === membership.userId) })).filter((item) => item.user); return <Panel title="Access & people" description="Review who can access this organisation. Invite and role changes live in People management."><div className="flex items-center gap-3 rounded-lg bg-muted/50 p-4"><ShieldCheck className="size-5 text-primary" aria-hidden="true" /><p className="text-sm text-muted-foreground">Invite-only access is enabled. Organisation admins control roles and location assignments.</p></div><div className="mt-5 divide-y rounded-lg border">{people.map(({ membership, user }) => <div key={membership.userId} className="flex items-center gap-3 p-4"><span className="grid size-9 place-items-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">{user?.name.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{user?.name}</p><p className="truncate text-xs text-muted-foreground">{user?.email}</p></div><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-medium">{membership.role.replaceAll("_", " ")}</span></div>)}</div></Panel> }
function Notifications({ emailAlerts, stockAlerts, setEmailAlerts, setStockAlerts, onSave, saved }: { emailAlerts: boolean; stockAlerts: boolean; setEmailAlerts: (value: boolean) => void; setStockAlerts: (value: boolean) => void; onSave: () => void; saved: boolean }) { return <Panel title="Notifications" description="Choose which operational updates you want to see."><Toggle label="Email activity summaries" description="Receive a daily summary of sales and transfers." checked={emailAlerts} onChange={setEmailAlerts} /><Toggle label="Low-stock alerts" description="Show a warning when a variant reaches two available units." checked={stockAlerts} onChange={setStockAlerts} /><button type="button" onClick={onSave} className={cn(buttonVariants(), "mt-6 min-h-11")}>{saved ? "Saved" : "Save notifications"}</button></Panel> }
function Panel({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div><div className="border-b pb-5"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div><div className="pt-6">{children}</div></div> }
function ReadOnly({ label, value }: { label: string; value: string }) { return <div className="space-y-1.5"><p className="text-sm font-medium">{label}</p><p className="rounded-md border bg-muted/30 px-3 py-2.5 text-sm text-muted-foreground">{value}</p></div> }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex cursor-pointer items-start gap-3 border-b py-4 last:border-0"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="mt-1 size-4 accent-primary" /><span><span className="block text-sm font-medium">{label}</span><span className="mt-1 block text-xs text-muted-foreground">{description}</span></span></label> }
