import { z } from "zod"

export function buildRugSku(productId: string, colour: string, lengthCm: number, widthCm: number) { const colourCode = colour.trim().split(/[\s-]+/).filter(Boolean).map((word) => word.slice(0, 2)).reverse().join("").toUpperCase(); return `${productId.trim().toUpperCase()}-${colourCode}-${lengthCm}${widthCm}` }

export const createProductSchema = z.object({
  organizationId: z.string().min(1), name: z.string().trim().min(2, "Enter a product name."), designNumber: z.string().trim().min(2, "Enter a design number."), category: z.string().trim().min(1, "Select a category."), collection: z.string().trim().min(2, "Enter a collection."), material: z.string().trim().min(2, "Enter a material."), barcode: z.string().trim().max(40), articleNumber: z.string().trim().max(40).optional(), colour: z.string().trim().min(2, "Enter a colour."), widthCm: z.number().int().positive("Width must be greater than zero."), lengthCm: z.number().int().positive("Length must be greater than zero."), retailPriceCents: z.number().int().nonnegative("Retail price cannot be negative."), costPriceCents: z.number().int().nonnegative("Cost price cannot be negative."), gstApplicable: z.boolean(), initialStock: z.number().int().nonnegative("Initial stock cannot be negative."), initialLocationId: z.string().min(1, "Select an initial location."),
})

export const adjustInventorySchema = z.object({ organizationId: z.string().min(1), variantId: z.string().min(1, "Select a product variant."), locationId: z.string().min(1, "Select a location."), quantityChange: z.number().int().refine((value) => value !== 0, "Adjustment cannot be zero."), reason: z.string().min(1, "Select a reason."), notes: z.string().trim().min(4, "Add a short note explaining the adjustment.") })
export const createVariantSchema = z.object({ organizationId: z.string().min(1), productId: z.string().min(1), sku: z.string().trim().min(3).max(40).transform((value) => value.toUpperCase()), supplier: z.string().trim().min(2), articleNumber: z.string().trim().min(1), barcode: z.string().trim().min(1), colour: z.string().trim().min(2), description: z.string().trim().min(10), origin: z.string().trim().min(2), material: z.string().trim().min(2), design: z.string().trim().min(2), category: z.string().trim().min(1), features: z.array(z.string()).default([]), tags: z.array(z.string()).default([]), usedIn: z.array(z.string()).default([]), widthCm: z.number().positive(), lengthCm: z.number().positive(), heightCm: z.number().nonnegative(), weightKg: z.number().nonnegative(), costPriceCents: z.number().int().nonnegative(), retailPriceCents: z.number().int().nonnegative(), gstApplicable: z.boolean(), reorderLevel: z.number().int().nonnegative(), initialStock: z.number().int().nonnegative(), initialLocationId: z.string().min(1) })
