import type { DevelopmentSession, MembaData } from "./types"
import { seedInventory, seedMovements, seedProducts, seedVariants } from "./catalogue-seed"

export const seedData: MembaData = {
  schemaVersion: 1,
  organizations: [
    {
      id: "org-hearth-home",
      name: "Hearth & Home Retail",
      code: "HHR",
      status: "ACTIVE",
      locationIds: [
        "loc-richmond",
        "loc-preston",
        "loc-dandenong",
        "loc-geelong",
        "loc-warehouse",
      ],
      memberIds: ["user-sumit", "user-maya", "user-john", "user-amelia"],
      salesTodayCents: 2845000,
      orderCountToday: 34,
      inventoryCount: 1885,
    },
    {
      id: "org-weave-living",
      name: "Weave Living Co.",
      code: "WLC",
      status: "TRIAL",
      locationIds: ["loc-fitzroy", "loc-weave-warehouse"],
      memberIds: ["user-sumit", "user-noah"],
      salesTodayCents: 672000,
      orderCountToday: 9,
      inventoryCount: 462,
    },
  ],
  locations: [
    {
      id: "loc-richmond",
      organizationId: "org-hearth-home",
      name: "Richmond Rug Gallery",
      code: "RCH",
      type: "STORE",
      suburb: "Richmond",
      state: "VIC",
      active: true,
    },
    {
      id: "loc-preston",
      organizationId: "org-hearth-home",
      name: "Preston Home",
      code: "PRE",
      type: "STORE",
      suburb: "Preston",
      state: "VIC",
      active: true,
    },
    {
      id: "loc-dandenong",
      organizationId: "org-hearth-home",
      name: "Dandenong Rugs",
      code: "DAN",
      type: "STORE",
      suburb: "Dandenong",
      state: "VIC",
      active: true,
    },
    {
      id: "loc-geelong",
      organizationId: "org-hearth-home",
      name: "Geelong Interiors",
      code: "GEE",
      type: "STORE",
      suburb: "Geelong",
      state: "VIC",
      active: true,
    },
    {
      id: "loc-warehouse",
      organizationId: "org-hearth-home",
      name: "Main Warehouse",
      code: "WH1",
      type: "WAREHOUSE",
      suburb: "Truganina",
      state: "VIC",
      active: true,
    },
    {
      id: "loc-fitzroy",
      organizationId: "org-weave-living",
      name: "Fitzroy Showroom",
      code: "FIT",
      type: "STORE",
      suburb: "Fitzroy",
      state: "VIC",
      active: true,
    },
    {
      id: "loc-weave-warehouse",
      organizationId: "org-weave-living",
      name: "Weave Warehouse",
      code: "WWH",
      type: "WAREHOUSE",
      suburb: "Coburg",
      state: "VIC",
      active: true,
    },
  ],
  users: [
    {
      id: "user-sumit",
      name: "Sumit Saggar",
      email: "sumit@memba.dev",
      initials: "SA",
      active: true,
    },
    {
      id: "user-maya",
      name: "Maya Chen",
      email: "maya@hearthhome.test",
      initials: "MC",
      active: true,
    },
    {
      id: "user-john",
      name: "John Bell",
      email: "john@hearthhome.test",
      initials: "JB",
      active: true,
    },
    {
      id: "user-amelia",
      name: "Amelia Ross",
      email: "amelia@hearthhome.test",
      initials: "AR",
      active: true,
    },
    {
      id: "user-noah",
      name: "Noah Williams",
      email: "noah@weaveliving.test",
      initials: "NW",
      active: true,
    },
  ],
  memberships: [
    {
      id: "membership-super",
      userId: "user-sumit",
      organizationId: null,
      role: "SUPER_ADMIN",
      locationIds: [],
    },
    {
      id: "membership-hearth-admin",
      userId: "user-maya",
      organizationId: "org-hearth-home",
      role: "ADMIN",
      locationIds: [
        "loc-richmond",
        "loc-preston",
        "loc-dandenong",
        "loc-geelong",
        "loc-warehouse",
      ],
    },
    {
      id: "membership-hearth-manager",
      userId: "user-john",
      organizationId: "org-hearth-home",
      role: "STORE_MANAGER",
      locationIds: ["loc-richmond", "loc-preston"],
      approvalCode: "2468",
    },
    {
      id: "membership-hearth-user",
      userId: "user-amelia",
      organizationId: "org-hearth-home",
      role: "STORE_USER",
      locationIds: ["loc-richmond"],
    },
    {
      id: "membership-weave-admin",
      userId: "user-noah",
      organizationId: "org-weave-living",
      role: "ADMIN",
      locationIds: ["loc-fitzroy", "loc-weave-warehouse"],
    },
  ],
  activity: [
    {
      id: "activity-1",
      organizationId: "org-hearth-home",
      title: "Sale MEM-RCH-10432 completed",
      description: "$1,800.00 · EFT · Richmond",
      timestamp: "10 minutes ago",
      kind: "SALE",
    },
    {
      id: "activity-2",
      organizationId: "org-hearth-home",
      title: "Transfer TRN-204 approved",
      description: "Main Warehouse → Preston · 6 items",
      timestamp: "28 minutes ago",
      kind: "TRANSFER",
    },
    {
      id: "activity-3",
      organizationId: "org-weave-living",
      title: "Weave Living Co. started trial",
      description: "Organization created by Sumit Saggar",
      timestamp: "Yesterday",
      kind: "ORGANIZATION",
    },
    {
      id: "activity-4",
      organizationId: "org-hearth-home",
      title: "Stock adjustment recorded",
      description: "PH302-RD-200300 · Richmond · −1 damaged",
      timestamp: "Yesterday",
      kind: "INVENTORY",
    },
  ],
  auditLogs: [],
  products: seedProducts,
  variants: seedVariants,
  inventory: seedInventory,
  inventoryMovements: seedMovements,
  orders: [],
  transfers: [],
  dailyRegisters: [],
}

export const defaultDevelopmentSession: DevelopmentSession = {
  userId: "user-sumit",
  organizationId: null,
  membershipId: "membership-super",
}
